### ISSUE TITLE
Can we have the option to announce who can use the interactables in Court of Stars in chat?

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#112]
It's really neat that it was added to tell us who can use one of them. Like I just had it tell me my demon hunter friend could use the skinning one and I had no idea he was a skinner.

Maybe an alternative would be a box or something for it somewhere like the spy section? But I wouldn't know when it should pop up or go away.

It's just hard to reference it after it pops up (usually during combat) and goes away since it prints so it's not in my chat tab.

**Comment by MysticalOS** [comment]
I'm just weary about keeping box on screen a long time. But I suppose as an option somewhere.

**Comment by gotex007** [comment]
Yeah I'm concerned about it too. I'm not sure what the best option is but I'd like to be able to reference the information easier.

Is there a way to make it trigger from slightly further away too if we store/say the information? I don't think it triggers on the engineer orb since generally groups avoid the house it's in unless we can see it's in there and have an engie/gnome/goblin. It's not necessary but it'd be nice if we could be notified of it being there without having to run past it and peek in the doorway, granted this is blizzard's fault for the way they designed the dungeon.

**Comment by MysticalOS** [comment]
it triggers on mouseover of object by anyone in party using DBM or littlewigs. from unlimited distance. So you just have to see an object, and mouse over it

**Comment by gotex007** [comment]
Oh I guess it just coincidentally happened when I was mousing over for a weakaura I have that can't tell if anyone can actually use it. I'd like to ditch the weakaura one for a couple of reasons like it getting called in chat multiple times if multiple people have it. I look forward to the solution you implement.
