### ISSUE TITLE
Dungeon Mob Ability Timers

### ISSUE THREAD

**Issue by Noblefour** [DeadlyBossMods/DBM-Dungeons#114]
It would be helpful if the timer bars for dangerous abilities cast by certain mobs (Ex: Narcotic burst in SBG, tidal burst in TJS, Tectonic slam in RLP, etc) in dungeons had the function to where if the NPC has a marker on them, then the corresponding timer bar for their dangerous ability (Mentioned above) will also have same marker on it. The reason for this is sometimes if the spiders in SBG for example end up casting "Necrotic Burst" but staggered by 1-2 seconds then I have trouble knowing which spider will cast "Necrotic Burst" first. I use a M+ auto marker Weak Aura that marks all the mobs automatically so I can assign kicks easier and so knowing which timer bar is for each marker spider I know when my marked spider will cast "Necrotic Burst" if the spiders casts were staggered by 1-2 seconds. Right now i'm having to guess which timer bar is for which NPC in dungeons with multiple of the same caster NPC in 1 mob or a double pull

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DBM-Unified/issues/5 is more likely solution that's needed. Been talking with plater maintainer about mayb doing something there since it's looking less likely a solution built directly into DBM is in cards. its more likely there will be a new feature soonish™ where DBM can send timers to plater or something and display them there.

**Comment by Noblefour** [comment]
if @QartemisT could do that then that would be the feature I'm looking for!

**Comment by MysticalOS** [comment]
This was effectively done for S2 with plater integration (and end of season 1 briefly).

I'll leave issue open until such a time that it works without plater as well.

**Comment by MysticalOS** [comment]
Closing since https://github.com/DeadlyBossMods/DBM-Unified/issues/5 tracks core implimentation
