### ISSUE TITLE
Violet Hold bosses not registering

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-Dungeons#14]
**Describe the bug**
Just ran heroic and normal Violet Hold WotLK and out of all bosses only one registered as killed, other ones showed nothing, no messages about combat start, no wipes/victories in statistics.

**Do you have an error log of what happened?**
I have [transcriptor log](https://gist.github.com/Molkree/4d4b195395abb10c860770c1b923a8f3) of last two bosses on normal, none of them registered.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
r22-1

**Was it working in a previous version? If yes, which was the last good one?**
Not sure, but most likely.

**Additional context**
I was running with DBM debug on and didn't get any messages about encounter start/end, nothing at all. But I did get messages about portal #, "Boss incoming" and "Combat starts in ..." on last boss.

**Comment by MysticalOS** [comment]
without encounter events, dbm is just not gonna register one shots. if blizz has no events it can't be fixed. the legacy checks check if unit is affecting combat but if it's already dead it's not affecting combat anymore.

**Comment by Molkree** [comment]
Then I guess it can be closed if it's on Blizz.
