### ISSUE TITLE
Heartsbane Triad's skull marker for the Focusing Iris stops following the Iris after it marks each boss once.

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#153]
After it marks each boss once and the first boss takes the Iris again, it doesn't move to the first boss again. We had to pull it twice this run and it stopped. As far as I'm aware I don't have any other weakaura or addon messing with marking those bosses or using the skull marker during that boss fight.

**Comment by MysticalOS** [comment]
Oh good call, i already know how to fix that cause I had to fix it on yogg. damn wish i had caught this BEFORE i tagegd like literaly 5 min ago :D

**Comment by gotex007** [comment]
Gotcha. I forgot to mention I'm using whatever alpha that was prior to what you just pushed, so the version prior to r105.

**Comment by gotex007** [comment]
It didn't mark at all in the Waycrest I just ran.

**Comment by MysticalOS** [comment]
Where you group leader?
