### ISSUE TITLE
Entangling is not announced after latest update.

### ISSUE THREAD

**Issue by Mely2k1** [DeadlyBossMods/DBM-Dungeons#154]
**Describe the bug**

There used to be a countdown to Entangling, now there is nothing.
**Do you have an error log of what happened?**

No errors.
**To Reproduce**

Anytime Entangling happens in a m+ dungeon.
**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes
**Which version of DeadlyBossMods are you using?**
DBM-Party-Dragonflight-r109
**Was it working in a previous version? If yes, which was the last good one?**
Yes.  r108.
**Additional context**

**Comment by Mely2k1** [comment]
I finally figured out the problem!  I installed this weak aura this week https://wago.io/UpgradeRankTooltipRenamer and it just completely disabled the affix stuff from DBM.  I have no idea why but after deleting it, everything is working fine again.  Who would have thought a tooltip weak aura would muck things up so much!

**Comment by MysticalOS** [comment]
if it was improperly accessing DBM features and causing errors, maybe
