### ISSUE TITLE
Acid Barrage from the Ravager in ToTT tells the tank to use a defensive.

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#160]
Acid Barrage from the Ravager in ToTT tells the tank to use a defensive when it just targets a random player and sprays a cone.

**Comment by MysticalOS** [comment]
The guides said it targets tank and tank can aim it, is that not true? wouldn't surprise me considering the wowhead guides are quite inaccurate for dungeons

**Comment by gotex007** [comment]
Yeah it targets anybody else BUT the tank and sprays hitting everyone in the cone, which can include the tank.
