### ISSUE TITLE
EVERBLOOM ARCHMAGE SOL TIMERS

### ISSUE THREAD

**Issue by Hatyorok** [DeadlyBossMods/DBM-Dungeons#176]
Archmage Sol's timers for the combos don't display the correct combos. This has been going on for a while and can be difficult to know which combo is coming if you don't remember from memory. Would you be able to look into this?

From memory, this is the order and what isn't correct in DBM.
Fire (correct in DBM)
Fire / Frost (correct in DBM)
Frost / Arcane (correct in DBM)
Arcane / Fire (incorrect in DBM)
Repeat at Fire / Frost

**Comment by MysticalOS** [comment]
The way the fight is supposed to work (when it doesn't bug) is

Fire
Frost + Previous (fire)
Arcane + Previous (frost)
Fire + Previous (arcane)
Frost + Previous (Fire)

you get the idea

As you state. DBM is coded to do it this way. I don't see any situation it shows wrong timers unless the boss actually chooses wrong abilities.

DBM is coded to just start timer for next + previous. it's not a hard coded table at all, it does next + previous every time in code.

**Comment by Hatyorok** [comment]
I was about to link a VOD from my buddy for the fight, but yeah I see your edit:
https://www.youtube.com/watch?v=-OwXL2Qc9oU

Around 23:50 is the issue.

I've been doing it enough that I have it down for the most part, but I just ran one and completely blanked on it lol

I'm glad you saw it! looking forward to the fix.

**Comment by MysticalOS** [comment]
It's just annoying to work around a blizzard bug that was reported a year ago, twice. I really don't know why i even bother anymore. They haven't fixed a single bug I've reported in a long long time. I bet the boss still bugs out too and resets order at random as well.

**Comment by Hatyorok** [comment]
100% agree! Blizz only fixes fun bugs, like the mind control Swarmer bug... They don't do anything to the actual bugs in the game...

It worked fine (I think) the first couple weeks of the season, then something changed and it hasn't lined up since.

I haven't come across the order resetting yet, but I wouldn't doubt that happens. I'm sure some groups have blown CDs expecting the firestorm only to be surprised when it's ice/ arcane.

I greatly appreciate the quick responses! I switched from Little Wigs a little bit ago because DBM's trash timers are such a life saver in keys and really nice to have. So thank you for the hard work!

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DBM-Dungeons/commit/e1e7dcfdb0eb8d5f7d43da2caffa169fb719dc15 (and commit after it) should solve issue. fixed two bugs
One where it actually just started wrong object, (so one was my fault due to bad copy/paste)
and other works around boss/add inverting their casts. so it's fixed 2x.

**Comment by MysticalOS** [comment]
Leaving open to confirm didn't break anything with fixes, but it should be solid now, unless boss actually hard resets order then it'll be wrong but that's too annoying to attempt to work around, but at least that bug is less frequent.
