### ISSUE TITLE
WoW Classic Era V1.15.1 latest release no longer working (03/16/2024)

### ISSUE THREAD

**Issue by maximus210793** [DeadlyBossMods/DBM-Dungeons#177]
Hi,
I am playing WoW Classic Era V1.15.1.
Since the latest release DBM is no longer opening ingame (Release: (03/16/2024))
Thanks for fixing it.

**Comment by MysticalOS** [comment]
Answered https://github.com/DeadlyBossMods/DBM-BCVanilla/issues/108
closed this duplicate
