### ISSUE TITLE
DBM - Dungeons & Events (Requires Deadly Boss Mods) - Virus Detected by Windows Defender

### ISSUE THREAD

**Issue by Toolazy2work** [DeadlyBossMods/DBM-Dungeons#182]
**Describe the bug**
When downloading the zip file, windows defender detects a virus Trojan:Script/Wacatac.B!ml.  this happens when downloading directly or when downloading via curseforge

**Do you have an error log of what happened?**
NA

**To Reproduce**

1. Go to Curseforge and download said mod
2. Windows defender blocks the download as it detects a virus

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
NA

**Which version of DeadlyBossMods are you using?**
r124

**Was it working in a previous version? If yes, which was the last good one?**
Yes

**Additional context**
![2024-04-20 00_55_27-Windows Security](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/2252852/aae0bc5b-ac97-4335-95ef-4b5abc983d2c)

**Comment by MysticalOS** [comment]
It's an invalid report, it happens once a year
https://github.com/DeadlyBossMods/DeadlyBossMods/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+defender

(lots more issues on various projects here and there. Everything in that zip is publically viewable in this repo. Packaging is nothing special, it runs through another open source community packager that uploads the packaged files from this repo to addon sites without adding or changing any files (besides setting revision)
