### ISSUE TITLE
M+ Nokhud and Brackenhide timer errors

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#187]
**Do you have an error log of what happened?**
Transcript attached
[transcript.zip](https://github.com/DeadlyBossMods/DBM-Dungeons/files/15137126/transcript.zip)

**Screenshots**
![WoWScrnShot_042724_123225](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/d53e8a07-706b-4f8b-8281-5c61ffb6b7c0)
![WoWScrnShot_042724_123358](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/a7c1ab46-855d-48f1-968d-29c607d214fa)
![WoWScrnShot_042724_123441](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/43b6781d-39d9-46fc-ae73-bc83fa6e2b3c)
![WoWScrnShot_042724_124013](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/98f4541c-2330-46b5-9923-a8ab3d3d6908)
![WoWScrnShot_042724_130008](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/73ec0cf3-3fee-499d-b200-e6e396cf268b)

**Which version of DeadlyBossMods are you using?**
DBM-Dungeons r124-17 alpha
DBM-Core 10.2.36-21 alpha

**Comment by MysticalOS** [comment]
Nokhud timers were invalid report, those were already fixed a day earlier, but latest alpha wasn't installed.
Others were fixed
