### ISSUE TITLE
M+ Timer errors in Halls of Infusion, and missing nameplate warnings in Nokhud Offensive

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#192]
**Describe the bug**
1. Various timer errors in Halls of Infusion.
2. Missing nameplate timers in Nokhud Offensive:
 - Nokhud Warspear - Charge (not the actual name)
 - Desecrated Ohuna - Rotting Wind
 - Risen Mystic - Swift Wind
 - Batak - Bloodcurdling Shout

**Do you have an error log of what happened?**
[transcript.zip](https://github.com/DeadlyBossMods/DBM-Dungeons/files/15145179/transcript.zip)

**Screenshots**
![WoWScrnShot_042924_104116](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/d2a18ac1-2847-4d91-8846-b61a3abf6860)
![WoWScrnShot_042924_104551](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/ef283be3-8a99-4173-a839-569acfd856f4)
![WoWScrnShot_042924_104632](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/a787a8f8-d970-4ad4-b40b-1f678b822b95)

**Which version of DeadlyBossMods are you using?**
DBM-Core 10.2.36-44 alpha
DBM-Dungeons r125

**Comment by MysticalOS** [comment]
nevermind I see the bug. cause of wrong spell option keys
