### ISSUE TITLE
Halls of Infusion - Khajin not sending warnings for Frost Cyclone

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#194]
**Describe the bug**
Halls of Infusion - Khajin is not sending any DBM warnings for Frost Cyclone

**Do you have an error log of what happened?**
[hoi.zip](https://github.com/DeadlyBossMods/DBM-Dungeons/files/15185737/hoi.zip)

**Which version of DeadlyBossMods are you using?**
DBM-Dungeons r125-6 alpha

**Comment by MysticalOS** [comment]
Looks like a blizzard nerf to addons here. They broke the bosses target during target scan. So it's no longer possible to warn who it's on. all I can do is add a generic "Beware" type warning to it now and delete the chat yell
