### ISSUE TITLE
More R7 LowerBlackrockSpire LUA Errors

### ISSUE THREAD

**Issue by BluespiritWoW** [DeadlyBossMods/DBM-Dungeons#2]
Been getting more errors for lower blackrock and other dungeons without entering them.

12x ...y-Classic\LowerBlackrockSpire\OverlordWyrmthalak.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[C]: in function `error'
DBM-Core\DBM-Core-8.1.18.lua:7348: in function `NewMod'
...y-Classic\LowerBlackrockSpire\OverlordWyrmthalak.lua:1: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-8.1.18.lua:4043: in function `LoadMod'
DBM-Core\DBM-Core-8.1.18.lua:3991: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-8.1.18.lua:3951: in function `func'
DBM-Core\DBM-Core-8.1.18.lua:1618: in function <DBM-Core\DBM-Core.lua:1609>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

14x ...Ons\DBM-Party-Classic\LowerBlackrockSpire\Gizrul.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[C]: in function `error'
DBM-Core\DBM-Core-8.1.18.lua:7348: in function `NewMod'
...Ons\DBM-Party-Classic\LowerBlackrockSpire\Gizrul.lua:1: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-8.1.18.lua:4043: in function `LoadMod'
DBM-Core\DBM-Core-8.1.18.lua:3991: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-8.1.18.lua:3951: in function `func'
DBM-Core\DBM-Core-8.1.18.lua:1618: in function <DBM-Core\DBM-Core.lua:1609>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

16x ...ns\DBM-Party-Classic\LowerBlackrockSpire\Halycon.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[C]: in function `error'
DBM-Core\DBM-Core-8.1.18.lua:7348: in function `NewMod'
...ns\DBM-Party-Classic\LowerBlackrockSpire\Halycon.lua:1: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-8.1.18.lua:4043: in function `LoadMod'
DBM-Core\DBM-Core-8.1.18.lua:3991: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-8.1.18.lua:3951: in function `func'
DBM-Core\DBM-Core-8.1.18.lua:1618: in function <DBM-Core\DBM-Core.lua:1609>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

1x ...-Classic\LowerBlackrockSpire\QuartermasterZigris.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[C]: in function `error'
DBM-Core\DBM-Core-8.1.18.lua:7348: in function `NewMod'
...-Classic\LowerBlackrockSpire\QuartermasterZigris.lua:1: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-8.1.18.lua:4043: in function `LoadMod'
DBM-Core\DBM-Core-8.1.18.lua:3991: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-8.1.18.lua:3951: in function `func'
DBM-Core\DBM-Core-8.1.18.lua:1618: in function <DBM-Core\DBM-Core.lua:1609>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

1x ...M-Party-Classic\LowerBlackrockSpire\UrokDoomhowl.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[C]: in function `error'
DBM-Core\DBM-Core-8.1.18.lua:7348: in function `NewMod'
...M-Party-Classic\LowerBlackrockSpire\UrokDoomhowl.lua:1: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-8.1.18.lua:4043: in function `LoadMod'
DBM-Core\DBM-Core-8.1.18.lua:3991: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-8.1.18.lua:3951: in function `func'
DBM-Core\DBM-Core-8.1.18.lua:1618: in function <DBM-Core\DBM-Core.lua:1609>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

1x ...lassic\LowerBlackrockSpire\ShadowHunterVoshgajin.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[C]: in function `error'
DBM-Core\DBM-Core-8.1.18.lua:7348: in function `NewMod'
...lassic\LowerBlackrockSpire\ShadowHunterVoshgajin.lua:1: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-8.1.18.lua:4043: in function `LoadMod'
DBM-Core\DBM-Core-8.1.18.lua:3991: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-8.1.18.lua:3951: in function `func'
DBM-Core\DBM-Core-8.1.18.lua:1618: in function <DBM-Core\DBM-Core.lua:1609>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

**Comment by MysticalOS** [comment]
I doubt you're using R7, I absolutely tested and r 7 fixed issues with r6.

**Comment by BluespiritWoW** [comment]
Double checking everything now, they could be old reports, if so I do apologize. Will erase all the old reports, and get back to you.
