### ISSUE TITLE
Ruby Life Pools and Brackenhide Hollow errors

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#200]
**Describe the bug**
1. Ruby Life Pools - last boss timer error
2. Brackenhide Hollow - Treemouth - Decay Spray will recast on a different target if mage/hunter uses invisibility or feign death. Not sure if this can be remedied.
3. Brackenhide Hollow trash - Fleshripper Vulture - Screech has no nameplate timer

**Do you have an error log of what happened?**
[transcripts.zip](https://github.com/DeadlyBossMods/DBM-Dungeons/files/15229509/transcripts.zip)

**Screenshots**
![WoWScrnShot_050724_114913](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/a41972ce-cd10-468c-952c-c6c35f20aa14)
![WoWScrnShot_050724_121701](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/5017264b-6353-4ebf-a414-c7b683a1fc86)
![WoWScrnShot_050724_121954](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/2d74f946-8059-4dc9-8865-19941e68ad44)

**Which version of DeadlyBossMods are you using?**
Dungeons r126-5

**Comment by MysticalOS** [comment]
Can't do anything about 3. none of mobs lived long enough to cast it twice.

```				"Screech-385029-npc:186246-000239A77B = pull:238.8", -- [112]
				"Screech-385029-npc:186246-0002B9A77B = pull:226.7", -- [113]```
two single casts in entire log.

**Comment by MysticalOS** [comment]
Gonna close this issue. a timer for screech is just not gonna happen

https://www.warcraftlogs.com/reports/nvTGDzx6fKd2Zb1J#fight=4&pins=2%24Off%24%23244F4B%24expression%24ability.id%20%3D%20385029%20and%20type%20%3D%20%22begincast%22&view=events

They don't even live long enough on an 18 to cast it twice. I can't find a single public log even with 15s and higher, where any single mob ever uses this ability twice.
