### ISSUE TITLE
Algethar Academy Crawth potentially incorrect timer?

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#209]
**Describe the bug**
Crawth - the first Deafening Screech timer expired but the mechanic did not happen. Not sure if this is natural variance.
No debug error

**Do you have an error log of what happened?**
[AA10 fort.zip](https://github.com/DeadlyBossMods/DBM-Dungeons/files/15385410/AA10.fort.zip)

**Screenshots**
Did not take any

**Which version of DeadlyBossMods are you using?**
Dungeons r129-4 alpha

**Comment by MysticalOS** [comment]
Posts original issue here https://github.com/DeadlyBossMods/DBM-Dungeons/issues/193

opens a new issue complaining i fixed original issue. 🤣
