### ISSUE TITLE
EJ_GetSectionInfo not supported on Classic

### ISSUE THREAD

**Issue by rdmqwerty** [DeadlyBossMods/DBM-Dungeons#212]
**Describe the bug**
i got an error message when running a dungeon - "EJ_GetSectionInfo not supported on Classic"

**To Reproduce**
1. Go to 'Grim Batol (heroic) in cataclysm'
2. Fight General Umbriss or Eurdax
3. Wait for adds to spawn

**Screenshots**
![image](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/118700184/021f2741-fc13-4012-8548-e7126689dfb9)

![image](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/118700184/68295176-1e20-4e7a-8dad-833fa5a8d76d)

**Which version of DeadlyBossMods are you using?**
DBM-Dungeons-r129

**Comment by MysticalOS** [comment]
Was fixed last week, I just forgot to tag update. i tagged today so just grab new update
