### ISSUE TITLE
Remix Normal Shado-Pan Monastery timer error

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#213]
**Describe the bug**
Timer error due to phasing boss too quickly

**Do you have an error log of what happened?**
[remix normal shadopan monastery.zip](https://github.com/DeadlyBossMods/DBM-Dungeons/files/15451137/remix.normal.shadopan.monastery.zip)

**Screenshots**
![WoWScrnShot_052724_104842](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/94429cb5-6491-4a69-995b-713be0e4fd29)

**Which version of DeadlyBossMods are you using?**
Dungeons r130-2

**Comment by MysticalOS** [comment]
Apparently I saw this same problem] and already fixed it
