### ISSUE TITLE
MOP Remix Heroic Temple of the Jade Serpent timer error

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#217]
**Describe the bug**
Liu Flameheart timer error

**Do you have an error log of what happened?**
[heroic temple jade serpent.zip](https://github.com/user-attachments/files/15524261/heroic.temple.jade.serpent.zip)

**Screenshots**
![WoWScrnShot_060224_094224](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/134947146/b9005018-03f6-4a64-9c1d-51df76377b9c)

**Which version of DeadlyBossMods are you using?**
Dungeons r131

**Comment by MysticalOS** [comment]
Worst part of that timer is i've already shortened it twice.

**Comment by jungheeMW** [comment]
If you need more logs than just this one, let me know.
