### ISSUE TITLE
M+ Neltharus wrong mechanic callout (spell queuing related?)

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#232]
**Describe the bug**
Magmatusk - Warning calls for Charge, but boss does a different mechanic instead.

**Do you have an error log of what happened?**
[Nelth11.zip](https://github.com/user-attachments/files/16278369/Nelth11.zip)

**Screenshots**
![charge no](https://github.com/user-attachments/assets/bb9ca26e-20b8-414a-8a37-823ec4f36f50)

**Which version of DeadlyBossMods are you using?**
Dungeons r139-3

**Comment by MysticalOS** [comment]
I can find no issue in this screen shot or log. if it said blazing charge was on you than it was. if the boss didn't cast it, it's cause the cast got interrupted by kiting or LOSing the boss
