### ISSUE TITLE
How do I turn off allied debuffs on enemies? (check screenshot)

### ISSUE THREAD

**Issue by aleex7932** [DeadlyBossMods/DBM-Dungeons#239]
I installed DBM Dungeons delves and events and now I have the debuffs from my allies overlapping on my personal debuffs. How do I turn them off????
![Screenshot 2024-08-02 233451](https://github.com/user-attachments/assets/2b5d2f66-f642-49e2-82b6-80e54f56e233)

**Comment by MysticalOS** [comment]
That's not debuffs from allies that's nameplate timers, but for some reason you have put your mod into test mode in this example.

For a full guide on how to configure or turn off this feature I suggest giving this setup video a look
https://www.youtube.com/watch?v=1LSs23k8AHU

**Comment by aleex7932** [comment]
I used test mode so I can show what I was talking about. The video helped me and I got what I wanted. Thank you!

**Comment by MysticalOS** [comment]
It's definitely a powerful feature once you adjust it around your UI needs. definitely give it some configuration and see what you can do with it. :)
