### ISSUE TITLE
[Fix request] Cata Classic Zul'Gurub: Toxic Link

### ISSUE THREAD

**Issue by DanyRahm** [DeadlyBossMods/DBM-Dungeons#243]
Sorry to label as a bug, but the other option seemed even less appropriate.

In the heroic Zandalari dungeon Zul'Gurub, there's an ability cast onto players by a named trash mob (Venomancer T'Kulu) and the boss (High Priest Venoxis) that is called Toxic Link. https://www.wowhead.com/cata/spell=96477/toxic-link

DBM suggests the player to stack when they get linked. However, when you spread ASAP and cause the link to break, you take far less total damage, than if you let it remain for its full duration.
Should a ranged and a melee be the target, it's common to have the ranged move away, allowing the melee more uptime on the trash or the boss. Maybe there's a way to add this little detail, too.

**Comment by MysticalOS** [comment]
Yeah that's not a bad idea, if two melee say group up, else say split?

**Comment by DanyRahm** [comment]
Yeah I guess. As a tank, I see some melee dps who run regardless but if you can have them stay, the better. Cheers

**Comment by DanyRahm** [comment]
Retracting earlier statement. Leaving the poison link running for its full duration will hurt massively. Best to always spread and break it as early as possible.

**Comment by MysticalOS** [comment]
Decided to change audio to say neither break or gather and instead leave it up to players to decide, cause i still see both strats viable depending on group and ultimately group should just decide instead of DBM in this case.
