### ISSUE TITLE
M+ Stonevault and City of Threads - timer errors and wrong warning type

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#266]
**Describe the bug**
1. General timer errors
2. Stonevault Trash: Smash Rock - This ability has a 60 yard range, can't really be dodged according to the warning

**Do you have an error log of what happened?**
[SV COT.zip](https://github.com/user-attachments/files/17172887/SV.COT.zip)

**Screenshots**
![WoWScrnShot_092824_121209](https://github.com/user-attachments/assets/bfb78a15-feb2-49b2-b749-21782fbcdf67)
![WoWScrnShot_092824_121833](https://github.com/user-attachments/assets/f2135ec3-fa72-47e9-ac80-844c9d396c14)
![WoWScrnShot_092824_124613](https://github.com/user-attachments/assets/48d8db69-599b-4e41-b80f-e4185b698def)
![WoWScrnShot_092824_125145](https://github.com/user-attachments/assets/a1e50180-1c2b-40dd-b2ab-4f10067224d1)
![WoWScrnShot_092824_125158](https://github.com/user-attachments/assets/ed1810f9-e978-49b0-8d9d-1119d4214bf0)
![WoWScrnShot_092824_125216](https://github.com/user-attachments/assets/90fc504e-8a37-4c90-ab4e-91f1452879dd)
![WoWScrnShot_092824_125224](https://github.com/user-attachments/assets/a404e145-4c21-4ce5-b1df-d45a9b05964f)
![WoWScrnShot_092824_125250](https://github.com/user-attachments/assets/2d86d6c9-b09c-48a4-87f0-516bb62a8426)

**Which version of DeadlyBossMods are you using?**
Dungeons r155-4 alpha

**Comment by MysticalOS** [comment]
Smash rock is a 60 yard frontal way i read it. giant knockback you can avoid no?

**Comment by jungheeMW** [comment]
Nope, unavoidable damage (unless out-ranged 60 yards away) + unavoidable (minor) knockback. The tooltip of the ability and graphic effect are both misleading. 

https://youtu.be/2E01CFf2hag?si=Mu4LVnB_8WreCtFs&t=2245
