### ISSUE TITLE
Task: Review and polish up Legion timewalking dungeons for 9.1.5

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Dungeons#27]
"Timewalking Dungeons: Black Rook Hold, Eye of Azshara, Darkheart Thicket, Vault of the Wardens, Neltharion’s Lair, and Court of Stars."

**Comment by MysticalOS** [comment]
First pass completed. Any additional passes will require logs of dungeons on timewalker or timewalker M+ difficulty

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/145686653-94428ba1-f9e2-4747-aac1-cce27a840498.png)
[Log](https://gist.github.com/Molkree/11e2a8146950ecdd41f2dfab6dcd4edc)

![image](https://user-images.githubusercontent.com/12860284/145686692-a58dc658-05fa-4102-9e73-2dfb0dd14561.png)
![image](https://user-images.githubusercontent.com/12860284/145686700-41647b72-4692-44c5-a4f9-a1250673e7f2.png)
[Log](https://gist.github.com/Molkree/58d1859d36364b28baabfa09b22969ad)

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/146453167-92b900f1-cec7-432b-ba08-9adb96c1950b.png)
![image](https://user-images.githubusercontent.com/12860284/146453176-07bdfafc-0a92-4d6d-b146-e8c6c39affa2.png)
[Log](https://gist.github.com/Molkree/59991d30bd08a94efddc0aa7a0b5b36a)

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/147295408-ac234fa5-3147-4eb7-8c50-a6fa5c73cae3.png)
![image](https://user-images.githubusercontent.com/12860284/147295423-b5794ce8-0f56-4849-b97a-ae55fa1fb251.png)
[Log](https://gist.github.com/Molkree/b9978d6e5914b9dfb0e61935d2da4b4b)

**Comment by MysticalOS** [comment]
All reported issues to date fixed. Leaving issue open since I know there will be more.
