### ISSUE TITLE
M+ City of threads - Coaglamation - Viscous Darkness 

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#279]
Possible user error, but [Viscous Darkness](https://www.wowhead.com/spell=441216/viscous-darkness) does not always have a timer.

[cot 5.zip](https://github.com/user-attachments/files/17266323/cot.5.zip)

**Which version of DeadlyBossMods are you using?**
Core 11.0.20-19 alpha
Dungeons r160

**Comment by MysticalOS** [comment]
I could not find any code issues anyways. i'll leave ticket open for now

**Comment by jungheeMW** [comment]
Found the "problem". There is a timer bar, as well as an announce, but the audio countdown is disabled by default. Same thing for Dark Pulse.

For Dark Pulse, I would recommend having the countdown on by default for Healers, as it is a very heavy hitting unavoidable AOE.
For Viscous Darkness, I'll leave that decision up to you (or other player feedback). It is a knockback that also deals moderate damage.

**Comment by jungheeMW** [comment]
Closing ticket as the warnings DO have a countdown audio, just off by default.
