### ISSUE TITLE
City of Threads - Fangs of the Queen rp timer

### ISSUE THREAD

**Issue by drudrutt** [DeadlyBossMods/DBM-Dungeons#280]
Would be nice to have at activation/rp timer for the second boss (Fangs of the Queen) in City of Threads. 
To my knowledge theres none whilst suppostly bigwigs got one.

as of:
DBM-core-11.0.21
DBM-Dungeons-r160

**Comment by MysticalOS** [comment]
Thanks for suggestion, i'll look into adding it.
