### ISSUE TITLE
M+ Dawnbreaker timer errors + Siege of Boralus transcript

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#281]
**Describe the bug**
1. Dawnbreaker - timer errors, Burning Shadows missing count?
2. Siege of Boralus - no errors, just transcript

**Do you have an error log of what happened?**
[transcripts.zip](https://github.com/user-attachments/files/17272471/transcripts.zip)

**Screenshots**
![WoWScrnShot_100724_102119](https://github.com/user-attachments/assets/33110447-e7a1-4706-9b8b-998c4111cfc0)
![WoWScrnShot_100724_102208](https://github.com/user-attachments/assets/c210771f-d9c6-4fbd-8d80-f08b2ea2f263)
![WoWScrnShot_100724_102330](https://github.com/user-attachments/assets/f4e28823-68fd-4108-bbe6-c61e8b036923)
![WoWScrnShot_100724_102335](https://github.com/user-attachments/assets/90c451e9-6175-4dc2-8a3d-0fcfddb96b2d)
![WoWScrnShot_100724_103733](https://github.com/user-attachments/assets/c40afb2a-bbbc-4723-be3d-aadeb2c54a81)

**Which version of DeadlyBossMods are you using?**
Dungeons r160 release - this is the latest version available on Curseforge

**Comment by MysticalOS** [comment]
those collapsing nights have bad counts still, i fixed that bug i'm confused. no way you had 5 casts in stage 2 with count resetting at 50%. it seems it's still failing to reset so loading wrong table values. grr
