### ISSUE TITLE
TWW Priory of the Sacred Flame timers

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-Dungeons#289]
**Describe the bug**

![image](https://github.com/user-attachments/assets/c6e70d0d-5e40-4d8a-b890-dc4bfb6bb473)

![image](https://github.com/user-attachments/assets/f975cada-6206-4119-8844-ed11f4b9435c)

**Do you have an error log of what happened?**

No autologging for normal dungeons so no.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
https://github.com/DeadlyBossMods/DBM-Dungeons/releases/tag/r161

**Was it working in a previous version? If yes, which was the last good one?**
Dunno

**Comment by Molkree** [comment]
![image](https://github.com/user-attachments/assets/85918fe8-0165-483d-a3a9-b70c1b637a9c)
another run
[Transcriptor.zip](https://github.com/user-attachments/files/17355948/Transcriptor.zip)

**Comment by MysticalOS** [comment]
First screenshots have no log/context
