### ISSUE TITLE
I haven't been getting some notifications recently and I don't know why.

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#299]
I'm not getting told when dark orb, heaving wretch, etc are targeting me and the say callouts haven't been working either, even in raid. This has been going on for awhile and I was hoping it was just a version fix. I'm on the alpha channel for faster updates too. I don't even know what to look at or check or how because the options are all turned on.

WowUp automatically updates every time an update is pushed, but I'll mention the versions i have right now.
DBM version: 11.0.20-29-gd16c11f
DBM Dungeons version: r163-12-g25e43c5

**Comment by MysticalOS** [comment]
I'd make sure mods are actually loading in game on current character. if it shows silver that means enabled on diff char but not current.

**Comment by gotex007** [comment]
They're enabled. I get a lot of DBM alerts. I get the bars. I get the timer and announcements. There are just some weird things I don't get like I mentioned. Blizzard thinks purple on purple on purple is a good idea and it's really hard to tell if I have dark orb on me or not. Blizzard things a tiny green arrow on green on green is a good idea and I literally wiggle to see if Blightbone moves when he's casting heaving wretch to find out if it's on me or not so I can move in time if it isn't me. I watch other people's say bubbles work in raid and in keys but mine don't. I just don't know what to do about it.

**Comment by MysticalOS** [comment]
Some investigating, i think the scan method for blight bone had a small chance to fail, so switched to a slower scan that will be slower but less prone to this failure.

The orb warning was just likely caught in alert aggregation. btw dbm won't warn if you are the target, only that it's being cast cause the targeting is a private aura. But the aoe warning might have been squelched if another dodge alert happened within last 3 seconds. I changed that to 2.5 aggregation but it might stll not show if DBM has recently told you to dodge something else. that's just nature of trash warnings. to avoid spammy experience, especially with large pulls, warnings of same time get combined and throttled. so you don't get told to dodge 3 diff spells at same time. you need only one dodge warning even if it's for 3 diff things at once.

**Comment by gotex007** [comment]
Okay. I'm just going to close this ticket, assuming it works properly with Blightbone (haven't been there yet) now and accepting that it can't do dark orb.
