### ISSUE TITLE
Anniversary World boss Ysondre timer errors

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#305]
**Describe the bug**
Ysondre timer errors

**Do you have an error log of what happened?**
[ysondre.zip](https://github.com/user-attachments/files/17534911/ysondre.zip)

**Screenshots**
![WoWScrnShot_102824_012953](https://github.com/user-attachments/assets/c63f32df-54aa-4100-8063-59abb3b381a1)
![WoWScrnShot_102824_013004](https://github.com/user-attachments/assets/99289f48-0be7-4dd5-b32b-7c8acce01078)

**Which version of DeadlyBossMods are you using?**
Dungeons r164-2 alpha

**Comment by Molkree** [comment]
Another log of her, might be less helpful as I only had 1.2 second off on the first ability
[Transcriptor.zip](https://github.com/user-attachments/files/17535106/Transcriptor.zip)
