### ISSUE TITLE
Various dungeon issues in Dawnbreaker and Siege of Boralus

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#306]
**Describe the bug**
1. Xally's Bargain: Ascendant - timer feels generally inaccurate. I'm sorry I don't have further details to provide.
2. Monks that talent into Pressure Points (ID: 450432) are able to soothe enrages with Paralysis (ID: 115078). However, even when Paralysis is on cooldown, monks will still get warnings to purge enraged targets, ignoring DBM's filter.
3. On the 2nd boss of Dawnbreaker, Anub'ikkaj - are the abilities semi-random when the boss uses them? I turned on audio countdowns for both Dark Orb and Shadowy Decay and I often get two audio countdowns at the same time.
4. Siege of Boralus - 1st boss Chopper Redhook - general timer error, and also a timer error produced right as the boss died.
5. Ara-Kara - 2nd boss Anub'zekt - timer error

**Do you have an error log of what happened?**
Transcripts include the following dungeons:
- Dawnbreaker
- Siege of Boralus
- Ara-Kara
- Grim Batol
[DB SOB AK GB.zip](https://github.com/user-attachments/files/17537672/DB.SOB.AK.GB.zip)

Older Siege of Boralus transcripts in tickets #302 and #297

**Screenshots**
<img width="542" alt="filter settings dbm" src="https://github.com/user-attachments/assets/dafd2270-8e03-4b49-9f6e-d28f9f342ff7">
![WoWScrnShot_102824_103224](https://github.com/user-attachments/assets/71bb39a9-bf46-4a16-b64b-4154defbc667)
![WoWScrnShot_102824_103241](https://github.com/user-attachments/assets/bf9653c4-5c50-4d56-b98e-6995a4752022)
![WoWScrnShot_102824_114206](https://github.com/user-attachments/assets/8cd63599-cf00-4a87-8e2a-63238f6ec6b9)

**Which version of DeadlyBossMods are you using?**
Core 11.0.24-4
Dungeons r164-2 alpha

**Comment by MysticalOS** [comment]
1 that's hard to solve, i'll look into it but it's really something that needs extensive debugging by me IN the dungeon
2 DBM has no filter for mob based dispels, only player based dispells or mob based interrupts.
3 EVERY boss in that dungeon has severe spell queuing issues. Nothing can be done about it. When two countedowns are at same time it's because EITHER ability might be next.
4. Duplicate of a previous issue that's now fixed
5. Pushing a fix for this one

**Comment by MysticalOS** [comment]
For number 1 the best thing you can do is run verbose debug mode in M+ which will log a crap ton more events for the experimental combat zone scanner., but it may make running the key suck cause you're screen will be spammed half to death

**Comment by jungheeMW** [comment]
> 2 DBM has no filter for mob based dispels, only player based dispells or mob based interrupts.

So does this mean that I will always get a warning to soothe, regardless of whether my ability is on cooldown or not?
> For number 1 the best thing you can do is run verbose debug mode (level 3) in M+ which will log a crap ton more events for the experimental combat zone scanner., but it may make running the key suck cause you're screen will be spammed half to death

Is the spam only in the chat window, or will it appear elsewhere on my screen? If it's only the chat window I can probably just ignore it.

**Comment by MysticalOS** [comment]
Just in chat window for spam.

and yes you'll always get sooth warning even if it's on cooldown. that tech hasn't not been developed yet for filters.

**Comment by jungheeMW** [comment]
Thank you for the clarification. I'll see what I can do about Xally timers.
