### ISSUE TITLE
GrimBatol,Stonevault, and other dungeons thrash packs habilities needed.

### ISSUE THREAD

**Issue by SantiCioh** [DeadlyBossMods/DBM-Dungeons#309]
My feature is to add the following habilities to be shown, since most are tankbusters and their damage is insanely high.
Shadow Claw from Voidbound Despoilers in Stonevault
Shadowflame Slash from Twilight Flamerender in Grim Batol

**Comment by MysticalOS** [comment]
Oh I forgot, this was on my todo list

Boneflay tank alert: Necrotic Wake
Shadow Claw tank alert: Ara Kara
Venom Strike: City of Threads

you mention one of them, i assume others accurate to? i'll add yours to this list and with ticket wn't forget now

**Comment by MysticalOS** [comment]
Maybe i had shadow claw dungeon wrong but not spellname

**Comment by MysticalOS** [comment]
I'll get em added within next day or so. been up all night so will probably unwind and rest a bit soon and get to that stuff later.
