### ISSUE TITLE
Timer errors with Siege of Boralus, Necrotic Wake (Affix: Devour)

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#312]
**Describe the bug**
1. Siege of Boralus - general timer errors
2. Necrotic Wake - Spine Crush error might be related to tank moving mob, Drain Fluids error possibly related to feign death?
3. Necrotic Wake trash - Rotspew - Spew Disease should have it's countdown audio default to ON for melee DPS (it hits hard and the players should be prepared)

**Do you have an error log of what happened?**
Siege of Boralus transcript is **NOT on debug mode** because I forgot.
Necrotic Wake is on debug level 2.
[SOB NW.zip](https://github.com/user-attachments/files/17595729/SOB.NW.zip)

**Screenshots**
![WoWScrnShot_110124_103322](https://github.com/user-attachments/assets/4cdb3305-3872-49f2-b47b-669fadea06d8)
![WoWScrnShot_110124_111756](https://github.com/user-attachments/assets/0b636bb0-678c-4db1-87de-c8565d66cf6c)
![WoWScrnShot_110124_111952](https://github.com/user-attachments/assets/14d0d83e-7e30-431f-bec1-f379e7ce1894)

**Which version of DeadlyBossMods are you using?**
Dungeons r165-2 alpha
Core 11.0.25-2 alpha

**Comment by Molkree** [comment]
I've got timer debug for Awaken Creation instead

<img width="378" alt="image" src="https://github.com/user-attachments/assets/dc281dac-c2d3-442b-8739-00e7f7c727a9">

[NecroticWake.zip](https://github.com/user-attachments/files/17610684/NecroticWake.zip)


that was on https://github.com/DeadlyBossMods/DBM-Dungeons/commit/829c21d11c8c8ae155444ce0155e05a053f2ded3
