### ISSUE TITLE
Transcriptor logs: DB, SV

### ISSUE THREAD

**Issue by linaori** [DeadlyBossMods/DBM-Dungeons#313]
Got 2 refresh warnings

[DawnBreaker.zip](https://github.com/user-attachments/files/17611422/DawnBreaker.zip)

**Comment by MysticalOS** [comment]
banned

**Comment by linaori** [comment]
Got a total of 3 warnings, 2 are small, 1 is rather large

[Stonevault.zip](https://github.com/user-attachments/files/17611716/Stonevault.zip)
