### ISSUE TITLE
Transcriptor log: Ara Kara, City of Echoes

### ISSUE THREAD

**Issue by linaori** [DeadlyBossMods/DBM-Dungeons#315]
There were some minor timers, also a bigger one on the last boss

[arakara.zip](https://github.com/user-attachments/files/17637108/arakara.zip)

**Comment by MysticalOS** [comment]
didn't see any big ones. a single 0.4 and a single 0.7

**Comment by linaori** [comment]
Hm I thought there was a 7.4 or something for the last boss, maybe I saw it incorrectly
