### ISSUE TITLE
Delve: The Underkeep timer error

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#317]
**Describe the bug**
Timer error on final boss

**Do you have an error log of what happened?**
[underkeep t10.zip](https://github.com/user-attachments/files/17686086/underkeep.t10.zip)

**Screenshots**
![WoWScrnShot_110924_124716](https://github.com/user-attachments/assets/4e5fd5ac-d7d2-4cda-b7cf-70cac1861ab1)
![WoWScrnShot_110924_124813](https://github.com/user-attachments/assets/d93c8849-4c1f-495d-a627-f96af30d03a6)

**Which version of DeadlyBossMods are you using?**
Core 11.0.25-24 alpha
Dungeons r168 release

**Comment by MysticalOS** [comment]
oh, you didn't have debugmode on so it didn't produce good logs for this. :( I'm just gonna enable experimental code for all users so I get better logs and it doesn't rely on limiting it to debug mode.
