### ISSUE TITLE
Transcriptor logs: Necrotic Wake

### ISSUE THREAD

**Issue by linaori** [DeadlyBossMods/DBM-Dungeons#318]
Timer Heaving Retch (1)(Timer320596cdcount-32.5) refreshed before expired. Remaining time is : 0.3
Timer Animate Dead(Timer321780cdnp-29.1) refreshed before expired. Remaining time is : 0.9
Timer Grim Fate(Timer327396cdnp-18.2) refreshed before expired. Remaining time is : 0.6
Timer Repair Flesh(Timer327130cdpnp-14.3) refreshed before expired. Remaining time is : 0.4

[necrotic-wake.zip](https://github.com/user-attachments/files/17688937/necrotic-wake.zip)

**Comment by MysticalOS** [comment]
ah you watched me on stream searching for "refreshed" in logs to find those and dug em out. A+
