### ISSUE TITLE
Transcriptor logs: Grim Batol

### ISSUE THREAD

**Issue by linaori** [DeadlyBossMods/DBM-Dungeons#319]
Timer Rive(Timer451378cdnp-17.1) refreshed before expired. Remaining time is : 0.5
Timer Reckless Tactic(Timer451379cdnp-15.2) refreshed before expired. Remaining time is : 2.1
Timer Molten Wake(Timer451965cdnp-16.1) refreshed before expired. Remaining time is : 0.3

[grim-batol.zip](https://github.com/user-attachments/files/17689243/grim-batol.zip)

**Comment by jungheeMW** [comment]
Timer |TInterface\\EncounterJournal\\UI-EJ-Icons.blp:20:20:0:0:255:66:6:21:7:27|tRive(Timer451378cdnp-17.1) refreshed before expired. Remaining time is : 0.5#2",
Timer |TInterface\\EncounterJournal\\UI-EJ-Icons.blp:20:20:0:0:255:66:6:21:7:27|tRive(Timer451378cdnp-17.1) refreshed before expired. Remaining time is : 1.6. 
Timer |TInterface\\EncounterJournal\\UI-EJ-Icons.blp:20:20:0:0:255:66:102:118:40:58|tReckless Tactic(Timer451379cdnp-15.2) refreshed before expired. Remaining time is : 4.6. 
Timer |TInterface\\EncounterJournal\\UI-EJ-Icons.blp:20:20:0:0:255:66:6:21:7:27|tRive(Timer451378cdnp-17.1) refreshed before expired. Remaining time is : 1.1. 

[grim batol 10.zip](https://github.com/user-attachments/files/17695041/grim.batol.10.zip)
