### ISSUE TITLE
Transcriptor log - Skittering Breach Delve tier 5, Shadow Realm story

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#322]
EDIT: Delve was actually tier 6, not 5.

**Transcriptor log**
[skittering breach shadow realm tier 5.zip](https://github.com/user-attachments/files/17787552/skittering.breach.shadow.realm.tier.5.zip)

**Which version of DeadlyBossMods are you using?**
Core 11.0.29 release
Dungeons r170 release

**Additional context**
Did this on a tier 6 so data may not be useful. I don't see anyone doing this on a tier 8 or higher because the gimmick of this story and delve boss is literally "What if the whole screen was black and you can't see anything, including mechanics?"

**Comment by MysticalOS** [comment]
what's context of report? any missing timers or alerts, any errors?

**Comment by jungheeMW** [comment]
The final boss of the delve gave the error that the boss was not supported.
