### ISSUE TITLE
Zekvir ?? difficulty timer errors

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Dungeons#332]
**Describe the bug**
This guy spell queues like crazy. Multiple timer errors.

I do recall Blizzard said that the fight is customized for different specs. I ran this on a Windwalker Monk.

**Do you have an error log of what happened?**
[zekvir level 2 incomplete.zip](https://github.com/user-attachments/files/17878480/zekvir.level.2.incomplete.zip)

**Which version of DeadlyBossMods are you using?**
Dungeons r171-8 alpha

**Comment by MysticalOS** [comment]
i probably forgot ot change some of them to AI timers. the wya boss is coded it's impossible to use real timers

**Comment by jungheeMW** [comment]
Well, in case you need additional data for whatever reason, just now I was able to beat him again, so here's a transcript with a complete run. Otherwise just close ticket I guess.

[zekvir level 2 complete.zip](https://github.com/user-attachments/files/17878719/zekvir.level.2.complete.zip)
