### ISSUE TITLE
Some wrong BfA timers

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-Dungeons#35]
**Do you have an error log of what happened?**
[Transcriptor log](https://gist.github.com/Molkree/2f016057f1bd156c286ad47a38685628)
[Log 2](https://gist.github.com/Molkree/3b49406d7ac6d860e51d1b8863652673)

EDIT
Fixed

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/149621074-ea0561b2-ce94-4d29-8bde-617c1a392cb7.png)
![image](https://user-images.githubusercontent.com/12860284/149621079-275bc749-0548-4d4d-98ef-37f89befe633.png)
[Log](https://gist.github.com/Molkree/c01631ba51a1283ebe6fd3d40b7040cf)

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/149677521-865b6c0b-eea1-4a19-974f-27cb8e58b775.png)
![image](https://user-images.githubusercontent.com/12860284/149677524-5d1a6520-0e7c-4530-ba3a-1a29c344d505.png)
[Log](https://gist.github.com/Molkree/6a47e573c5ee0b1b4feff9968236923d)

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/149757747-876ecac8-c4fc-46a2-bd69-f891454c2539.png)
[Log](https://gist.github.com/Molkree/35ade220e68a25f55789a4dabdcd52e6)

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/149827076-ff1c6ba4-a9b8-407b-a125-1533cae3c47c.png)
![image](https://user-images.githubusercontent.com/12860284/149827104-8f79fb1c-6564-46fa-afd1-f5a8ca9eb7df.png)
[Log](https://gist.github.com/Molkree/d1e74214e38725d938f965061083d0ca)

**Comment by MysticalOS** [comment]
Reopen if more are found, but make sure you update first to avoid seeing repeats :)
