### ISSUE TITLE
BFA Party Vol'kaal LUA Error

### ISSUE THREAD

**Issue by MNienaber27** [DeadlyBossMods/DBM-Dungeons#56]
every time BFA-Party module loads I get Lua error. Specifically when zoning into BFA Mechagon

**Comment by MysticalOS** [comment]
I investigated this and found no error. mod loads fine without any issues.

**Comment by MNienaber27** [comment]
Apologies for the notice. It appears to be an issue for my "DBM-Party-BFA\..." module an calls out "DBM-Core\modules\Scheduler.lua:162" 

Hope this is helpful. If not, you can close the issue.

**Comment by MysticalOS** [comment]
You get that on load?
