### ISSUE TITLE
r38 reported as infected with trojan

### ISSUE THREAD

**Issue by Baine** [DeadlyBossMods/DBM-Dungeons#58]
Windows defender reports (and blocks) the archive for r38 available here, on curse and wago as infected with ["Trojan:Script/Wacatac.H!ml"](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Wacatac.H!ml&threatid=2147814524)

assuming false positive since [virustotal reports it as completely free](https://www.virustotal.com/gui/file/f13a13553315ea9d7868444d14f222b5f387c7358233f7c64444ca7f16d263b0)

**Comment by MysticalOS** [comment]
It's false, just like last two times it happened. it flags addon for a week til enough users complain, they fix database and it goes away til next time it happens, usually within a year or two.

**Comment by Baine** [comment]
thanks for the reply :)

figured as much. couldn't find an existing issue/info on that, hence this one, even for future reference.

**Comment by minsis** [comment]
Just wanted to add more information to the thread as to what defender thinks it's supposed to be.

![image](https://user-images.githubusercontent.com/11248197/184027485-7b4a6975-6957-49cd-b336-ce02a4cf44e8.png)

**Comment by Larzous** [comment]
So, I understand this was closed because of the standard and repeating Wacatac trojan, which I can can manually allow via actions.  However, this new one I got doesn't allow me to allow the file:

This is `Trojan:Script/Sabsik.TE.A!ml`:
![image](https://user-images.githubusercontent.com/68357365/184278164-f7933f61-ca98-4a05-8326-5e1580e1f7de.png)

**Comment by Molkree** [comment]
> Any suggestions beyond turning defender off all together?

@Larzous, install alpha release of Dungeons if you are okay with it.

**Comment by Larzous** [comment]
1) I'm not sure how to do that
2) Today's update resolved the issue and I was able to successfully install via curse client.
