### ISSUE TITLE
Dbm not working with voicepack

### ISSUE THREAD

**Issue by razzz89** [DeadlyBossMods/DBM-Dungeons#63]
voice pack seems to have stopped working on dbm in all events  i leave dbm on default as i dont know what im doing i have selected the pack i want which is english female but am getting no warnings  some my friends have same problem where no voice is giving warning to interupt or any thing

**Comment by razzz89** [comment]
i have reinstalled from curse all dmb add on  all working now except interupts

**Comment by QartemisT** [comment]
DBM Interrupts is not an addon created or supported by us. I would recommend contacting the author for that addon. :)
