### ISSUE TITLE
Add warning for 'Shadow Prison' spell in Cataclysm Blackrock Caverns

### ISSUE THREAD

**Issue by TheLastDarkthorne** [DeadlyBossMods/DBM-Dungeons#71]
Hi! While this is not a super important thing but I think putting a very loud warning for [Shadow Prison](https://www.wowhead.com/spell=76686) spell would be good cause currently this ability is one-shotting people if they move out of the barely visible prison. DBM does not warn about this spell at all so a lot of people dies 'out of nowhere' while doing this dungeon on leveling or timewalking. It would be nice to have this added so people can know what is going on.

**Comment by Hammerpass** [comment]
same problem here
