### ISSUE TITLE
Court of Stars Spy Clues in Chat not working

### ISSUE THREAD

**Issue by Galthariel** [DeadlyBossMods/DBM-Dungeons#77]
**Describe the bug**

In the Court of Stars Spy event, I expect the addon to give the clues in the chat and nothing happens regardless to have both bottom options checked in the addon under Court of Stars

**Do you have an error log of what happened?**

No errors

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?
DBM-10.0.13.zip and DBM-Party-Dragonflight-r52

**Was it working in a previous version? If yes, which was the last good one?**
Back in Legion was working

**Additional context**

**Comment by MysticalOS** [comment]
Looking at code, i'm genuinely stumped as to cause, I don't see any obvious reason. Do you have lua errors turned on? It has to be erroring somehow because otherwise I see no reason it would fail if enabled.

**Comment by Galthariel** [comment]
No errors whatsoever. I use BugGrabber and BugSack

Unless I'm missing any other option besides the ones below. The addon is loading normally during CoS because I'm getting all the regular warnings for Trash and Boss fights.

![2022-12-27_17-38-06](https://user-images.githubusercontent.com/51491805/209720026-18cb9a27-f9d6-4e59-a0b2-3adb840d6219.png)

**Comment by MysticalOS** [comment]
No idea. I genuinely can't see any reason it wouldn't work. it's very straight forward code. "if option enabled, post to chat end" that's it. I've done dungeon  few times so I know the clue part working cause infoframe works fine, even still communicates with littlewigs. but I had post to chat disabled cause I find it redundant. if a user has dbm or LW they have an infoframe/box and don't need to spam chat. I guess there is a growing number of players though that have stopped using boss mods and instead use WA packs for everything that has to be considered now. Seems inefficient but that's kind of a new meta now too

**Comment by Galthariel** [comment]
I do see LittleWigs msgs in chat for those that uses it which is not my case. Anyways...thanks a lot for the help. I thought was me missing an option besides the checks above

**Comment by MysticalOS** [comment]
Definitely working in rewrite, so closing this
