### ISSUE TITLE
Court of Stars, Hint counter. 

### ISSUE THREAD

**Issue by MiLeX84** [DeadlyBossMods/DBM-Dungeons#85]
**Is your feature request related to a problem? Please describe.**
Not related to another problem. 
It is easier to find the hidden spy when all hints have been uncovered, but you need to know that all hints have been activated. 

**Describe the solution you'd like**
Add a counter or display that shows X hints of X have been discovered. The hints are all a game of time to time a key, so often have we missed a clue with randoms as we had no idea who talked to whom. 

**Describe alternatives you've considered**
add the counter to the info box like the hints, and perhaps post in chat the number of discovered hints and how many are still to be found.

**Additional context**
everything should be multilingual as folks in Europe play mostly with mixed groups using the group finder.

**Comment by QartemisT** [comment]
The hint counter has been added to the infobox in the latest alpha :)

**Comment by MysticalOS** [comment]
you mean release. it was in yesterdays release :P
