### ISSUE TITLE
Timers off on RP event TJS 2nd Boss(Strife and Pride)

### ISSUE THREAD

**Issue by Extort713** [DeadlyBossMods/DBM-Dungeons#95]
**Describe the bug**

I expected that the fight would start when the RP timer finished, yet it took another 3-5s before the fight actually started. This has been a re-occurring thing that happens every time for myself.

**Do you have an error log of what happened?**

**To Reproduce**
Start the fight and watch if the timer is misaligned.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
Release

**Was it working in a previous version? If yes, which was the last good one?**
No

**Comment by MysticalOS** [comment]
update dungeon mod, this is fixed in in latest update already.

**Comment by gotex007** [comment]
I just ran this on my ret pally and Strife specifically wasn't calling to swap but Peril was working properly.

**Comment by MysticalOS** [comment]
Works on both, based on target. if you weren't targeting it when it reached 7 stacks you got you alert. I've done this boss plenty to know it's working

**Comment by gotex007** [comment]
I definitely was targeting him. Just wanted to report the occurrence. Happened all 3 times he hit 7 stacks.

**Comment by gotex007** [comment]
> Works on both, based on target. if you weren't targeting it when it reached 7 stacks you got no alert. I've done this boss plenty to know it's working

It happened again today. I verified with my friends in the key that it was happening to them too. It would only call it for Peril and would not call it (not even once out of three times) on Strife. I have no idea what triggers it to do that. I mean it's not that big of a deal I guess and the season is ending soon anyway.

**Comment by MysticalOS** [comment]
i've done it myself, and watched it on stream, I've never seen it fail. and code wise, I see no reason for it to fail either unless for some reason the name is missing from combat log do to a missing translation. I guess I can hard code a fallback for missing name in combat log.

But the events are correct.
https://www.warcraftlogs.com/reports/H32cTrWYAvyjxQV4#fight=last&pins=2%24Off%24%23244F4B%24expression%24ability.id%20%3D%20113315&view=events&translate=true

they both use same one. if it works for one, it works for both

**Comment by gotex007** [comment]
Should I upload the log if it happens again? Would that help try to identify what triggers it? It's probably not worth worrying about at this point of the season but I just wanted to report that it had happened again and I verified with others that it happened at the time.

**Comment by MysticalOS** [comment]
nope. this issue will not be looked into at all cause it works fine for me and nothing wrong with code that logs would fix. either you have another mod breaking it, or you're encountering some obscure blizzard bug I couldn't work around anyways.
