### ISSUE TITLE
DBM doesn't announce to dispel The Raging Tempest's Energy Surge

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#98]
[I have the setting ticked but it doesn't tell my Warlock or my Hunter to dispel it. It's hard to see it on my nameplate because the boss is so tall so I really wish this notification actually happened.](https://i.imgur.com/HOhix34.png)

**Comment by MysticalOS** [comment]
Thanks for report, i have no idea how I missed that part of code still being commented out but it'll work in next update
